version: '3.7'

services:
  backend_prod:
    container_name: BackendProd_23_2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '25556:8080'
    volumes:
      - backend_prod_logs_23_2:/code/logs

volumes:
  backend_prod_logs_23_2:
